// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using f1_administraiton_API.Data;

#nullable disable

namespace f1_administraiton_API.Migrations
{
    [DbContext(typeof(RaceDbContext))]
    [Migration("20260725152757_added-seed-for-races")]
    partial class addedseedforraces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("f1_administraiton_API.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SelectedCurrency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coutry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitName = "Circuit de Monaco",
                            City = "Monte Carlo",
                            Coutry = "Monaco"
                        },
                        new
                        {
                            Id = 2,
                            CircuitName = "Red Bull Ring",
                            City = "Spielberg",
                            Coutry = "Austria"
                        },
                        new
                        {
                            Id = 3,
                            CircuitName = "Yas Marina Circuit",
                            City = "Abu Dhabi",
                            Coutry = "United Arab Emirates"
                        });
                });

            modelBuilder.Entity("f1_administraiton_API.Models.PaddockPass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DrinkAccess")
                        .HasColumnType("bit");

                    b.Property<decimal>("DrinkPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FoodAccess")
                        .HasColumnType("bit");

                    b.Property<decimal>("FoodPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("GarageAccess")
                        .HasColumnType("bit");

                    b.Property<decimal>("GaragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PassId")
                        .HasColumnType("int");

                    b.Property<bool>("PitLaneAccess")
                        .HasColumnType("bit");

                    b.Property<decimal>("PitLanePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.ToTable("PaddockPasses");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.Pass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrenctId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiscountDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PromoCodeId");

                    b.ToTable("Passes");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.PassZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassId")
                        .HasColumnType("int");

                    b.Property<int>("SeatingZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PassId");

                    b.HasIndex("SeatingZoneId");

                    b.ToTable("PassAndZones");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<bool>("isActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("isValid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PromoCodes");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EuroBasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GrandPrixName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalInfo = "Monaco street circuit race.",
                            EuroBasePrice = 500.00m,
                            GrandPrixName = "Monaco Grand Prix",
                            LocationId = 1
                        },
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "Austrian Grand Prix race.",
                            EuroBasePrice = 250.00m,
                            GrandPrixName = "Red Bull Ring",
                            LocationId = 2
                        },
                        new
                        {
                            Id = 3,
                            AdditionalInfo = "Season finale at Yas Marina Circuit.",
                            EuroBasePrice = 350.00m,
                            GrandPrixName = "Abu Dhabi GP",
                            LocationId = 3
                        });
                });

            modelBuilder.Entity("f1_administraiton_API.Models.RaceDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agenda")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceDays");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.SeatingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("RaceDayId")
                        .HasColumnType("int");

                    b.Property<int>("SeatingType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceDayId");

                    b.ToTable("SeatingZones");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.PaddockPass", b =>
                {
                    b.HasOne("f1_administraiton_API.Models.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.Pass", b =>
                {
                    b.HasOne("f1_administraiton_API.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("f1_administraiton_API.Models.PromoCode", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.PassZone", b =>
                {
                    b.HasOne("f1_administraiton_API.Models.Pass", "Pass")
                        .WithMany()
                        .HasForeignKey("PassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("f1_administraiton_API.Models.SeatingZone", "SeatingZone")
                        .WithMany()
                        .HasForeignKey("SeatingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pass");

                    b.Navigation("SeatingZone");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.Race", b =>
                {
                    b.HasOne("f1_administraiton_API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.RaceDay", b =>
                {
                    b.HasOne("f1_administraiton_API.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("f1_administraiton_API.Models.SeatingZone", b =>
                {
                    b.HasOne("f1_administraiton_API.Models.RaceDay", "RaceDay")
                        .WithMany()
                        .HasForeignKey("RaceDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceDay");
                });
#pragma warning restore 612, 618
        }
    }
}
